baseURL = "https://hs3.pl/"
languageCode = 'pl-pl'
paginate = 9
theme = "coHub"
title = 'Hackerspace Trójmiasto'
DefaultContentLanguage = "pl"
timeZone = "Europe/Warsaw"       # Note: make sure this is the same as in netlify.toml

[languages]
[languages.pl]
languageName = "🇵🇱"
contentDir = 'content/pl'

[languages.pl.params]
aboutPageURL = "blog"
contactLink = "/contact"
copyright = "© {year} Hackerspace Trójmiasto"
googleAnalytics = ""
logo = "/images/logo.png"
footerlogo = "/images/logo.png"
footerDescription = "Przyjdź i zbuduj coś z nami"

[languages.pl.params.address]
address = "al. Wojska Polskiego 41<br>80-268 Gdańsk"
email = "kontakt@hs3.pl"
openingDesc = "Otwarte całą dobę dla osób z kluczem."
openingHours = "Jeśli nie masz klucza [zapytaj na Discord](https://hs3.pl/join) czy ktoś jest w środku."
phone = "+48 661 691 133"

[languages.pl.params.events]
upcoming = "Nadchodzące"
past = "Przeszłe"
calendar = "Kalendarz"
icsLink = "Zaimportuj ten kalendarz"
icsLinkExplain = 'Pobierz ten plik i zaimportuj go do aplikacji kalendarza lub skopiuj adres URL łącza i użyj go jako "URL subskrypcji kalendarza". W ten sposób będziesz również otrzymywać aktualizacje.'

[languages.en]
title = "Hackerspace Trójmiasto (Three-city)"
contentDir = 'content/en'
languageName = "🇬🇧"

[languages.en.params]
aboutPageURL = "blog"
contactLink = "/en/contact"
copyright = "© {year} Hackerspace Trójmiasto"
googleAnalytics = ""
logo = "/images/logo.png"
footerlogo = "/images/logo.png"
footerDescription = "Come and build with us"

[languages.en.params.address]
address = "al. Wojska Polskiego 41<br>80-268 Gdańsk"
email = "kontakt@hs3.pl"
openingDesc = "Open 24/7 for members with a key."
openingHours = "For members without key and non-members: [ask on Discord](https://hs3.pl/join) if someone is there (in English or Polish)."
phone = "+48 661 691 133"

[languages.en.params.events]
upcoming = "Upcoming"
past = "Past"
calendar = "Calendar"
icsLink = "Import this calendar"
icsLinkExplain = 'Either download this file and import it into your calendar app, or copy the link URL, and use it as "Calendar subscription URL". In this way, you will also receive the updates.'

[params.map]
latitude = 54.3897425
longitude = 18.5815294
pinImage = "/images/pin.png"
pinUrl = "https://maps.app.goo.gl/GxMMjVquHcxkinQ2A"

[Menu]
# Main Menu
[[menu.Main]]
identifier = "about-us"
pageref = "/about"
weight = 1
[[menu.Main]]
identifier = "events"
pageref = "/wydarzenia"
weight = 2
[[menu.Main]]
identifier = "projects"
pageref = "/projekty"
weight = 3
[[menu.Main]]
identifier = "blogs"
pageref = "/blog"
weight = 4
[[menu.Main]]
identifier = "membership"
pageref = "/zasoby/czlonkostwo"
weight = 5
[[menu.Main]]
identifier = "resources"
pageref = "/zasoby"
weight = 6
[[menu.Main]]
identifier = "FAQ"
url = "/#faq"
weight = 7
[[menu.Main]]
identifier = "contact"
url = "/#contact"
weight = 8

# Sitemap Menu
[[menu.sitemap]]
name = "Privacy Policy"
url = "/privacy/"
weight = 1

# Social icons
[[params.social]]
icon = "ti-facebook"
url = "https://www.facebook.com/hackerspacetrojmiasto"
weight = 1
[[params.social]]
icon = "ti-twitter-alt"
url = "https://twitter.com/hs3city"
weight = 2
[[params.social]]
icon = "ti-linkedin"
url = "https://www.linkedin.com/company/hackerspace-tr%C3%B3jmiasto/"
weight = 2
[[params.social]]
icon = "ti-user"
url = "https://hs3.pl/join"
weight = 3
[[params.social]]
icon = "ti-youtube"
url = "https://www.youtube.com/channel/UC1MjdZvgtGZwSAaveL-Z8CA"
weight = 4
[[params.social]]
icon = "ti-video-camera"
url = "https://www.twitch.tv/hs3city"
weight = 5
[[params.social]]
icon = "ti-github"
url = "https://github.com/hs3city"
weight = 6
[[params.social]]
icon = "ti-wallet"
url = "https://patronite.pl/hs3/description"
weight = 7
[[params.social]]
icon = "ti-comments"
url = "https://kb.hs3.pl/"
weight = 8
